### ISSUE TITLE
Failure to sync blocks

### ISSUE THREAD

**Issue by rtkaczyk** [ScalaConsultants/Scorex#3]
relates to: https://github.com/ScalaConsultants/Scorex/pull/2

Steps to reproduce:
1. Build with assembly: `sbt "project elm" assembly`
2. Run 2 nodes:
* java -Dconfig.file=application-1.conf -jar target/elm.jar
* java -Dconfig.file=application-2.conf -jar target/elm.jar
3. Observe

You should get a stacktrace like this:

```
[ERROR] [11/07/2016 07:29:42.726] [elm-akka.actor.default-dispatcher-2] [akka://elm/user] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at scorex.core.network.NodeViewSynchronizer$$anonfun$processSyncStatus$1.applyOrElse(NodeViewSynchronizer.scala:125)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at scorex.core.network.NodeViewSynchronizer.aroundReceive(NodeViewSynchronizer.scala:32)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Hint: the value on which the assertion fails is produced by applying `Blockchain#continuationIds`. You may want to try to figure out what that method is supposed to do and whether we need to override it in `ElmBlockchain`.

**Comment by rtkaczyk** [comment]
Fixed by: babd6b2acf49ef4c9eefad88e8dc80b4f06555ac
